config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]
  resources :products do
    resources :comments
  end
  get 'simple_pages/about'
  get 'simple_pages/contact'
  root 'simple_pages#index'
  get 'simple_pages/landing_page'
  post 'simple_pages/thank_you'
  post 'payments/create'

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
 validates :name, presence: true
 has_many :orders
 has_many :comments, dependent: :destroy


 def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.rating_asc.first
  end
  def average_rating
   comments.average(:rating).to_f
  end

  def views
    $redis.get("product:#{id}")
  end

  def viewed!
    $redis.incr("product:#{id}")
  end


  def self.search(search_term)

    if Rails.env.development?
       @products = Product.where('name LIKE ?', "%#{search_term}%")

    elsif Rails.env.production?
       @products = Product.where('name ilike ?', "%#{search_term}%")
  end
 end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json

  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show

    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
    @product.viewed!

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price )
    end

end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = @products
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
            <p><%= comment.body %></p>
            <div class="rated" data-score="<%= comment.rating %>"></div>

         </div>
         <% if signed_in? && current_user.admin? %>
           <%= link_to 'Delete', product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
         <% end %>
    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
   <%= f.label :colour %><br>
   <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :price%><br>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_new_comment.erb
<% if signed_in? %>
 <h4>Add a review:</h4>
 <%= form_for([@product, @product.comments.build], remote: true) do |f| %>


 <p>
   <%= f.label :body, "Comments" %><br>
   <%= f.text_area :body %>
 </p>


 <p>
   <div class="rating"></div>
 </p>

 <p>
   <%= f.submit "Submit" %>
 </p>
 <% end %>
<% end %>

app/views/products/_product.html.erb
<div class="row">
    <div class="col-sm">
      <h3><u><%= link_to product.name, product %></u></h3>
      <p><%= product.description %></p>
      <strong>$ <%= product.price %></strong>
    </div><!-- /col -->
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>




   <% cache(cache_key_for_products) do %>
    <%= render @products %>
   <% end %>


<br>

<h4><%= link_to 'New Product', new_product_path %></h4>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name: Bike</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description: Great Bike</strong>
  <%= @product.description %>
</p>

<p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div> </p>


<span>
  Product views: <%= @product.views %>

</span>


<p>
  <strong>Color:</strong>
  <%= @product.colour %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>



<%= form_with(url: '/payments/create') do |form| %>
<%= render partial: "shared/stripe_checkout_button" %>
<%= hidden_field_tag(:product_id, @product.id) %>
<% end %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<article class="container products-show" data-product-id="<%= @product.id %>">
  <h1> Product:</h1>
  <p id="notice"><%= notice %></p>
  <!-- <div class="row align-items-center ratings-preview">
  <p class="col-sm">

  <i class="far fa-star"></i>
</p>
</div> -->
<!-- <strong>Image url:</strong> <%= @product.image_url %> -->
<section class="row">
  <div class="col-sm-6 img">
    <%= image_tag(@product.image_url, width: "300", class: "img-zoom", data_zoom_image: @product.image_url) %>



    <%= render 'new_comment' %>


  </div>
</section>
  <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>

  <%= render 'comments' %>



</article>



<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @comments %>
  </div>
  <%= will_paginate @comments, renderer: BootstrapPagination::Rails, :container => false %>

</div>