config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]
  resources :products do
    resources :comments
  end
  get 'simple_pages/about'
  get 'simple_pages/contact'
  root 'simple_pages#index'
  get 'simple_pages/landing_page'
  post 'simple_pages/thank_you'
  post 'payments/create'

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsProject</title>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

<meta name="viewport" content="width=device-width, initial-scale=1">
<%= csrf_meta_tags %>
</head>
<body>
  <div class="page-wrap">
    <div class="navbar">
      <div class="logo">Isavek</div>
      <div class="list">
        <ul>
         <li class="list-item"><%= link_to "Home", root_path %></li>
         <li class="list-item"><%= link_to "Products", products_path %></li>
         <li class="list-item"><%= link_to "About", simple_pages_about_path %></li>
         <li class="list-item"><%= link_to "Contact", simple_pages_contact_path %></li>
         <li class="list-item"><%= link_to 'Orders', orders_path %></li>
       </ul>
       <ul class="navbar-nav ml-auto">
   <% if user_signed_in? %>
   <li class="nav-item">
     <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
   </li>
   <% else %>
   <li class="nav-item">
     <%= link_to('Login', new_user_session_path, class: "nav-link") %>
   </li>
   <% end %>

 </ul>
    <div class="search">
       <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
       <%= form.label :q, 'Search for:' %>
       <%= form.text_field :q, id: 'q', value: params[:q] %>
       <%= form.submit 'Search' %>
     <% end %>
    </div>
</div>
    </div>
<p>Welcome! The date and time is <%= Time.now %></p>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</div>
<footer class="site-footer">
  &copy; 2018 Bike Berlin
</footer>


</body>
</html>